name: Run jalien-setup and test-suite
on:
  pull_request:
    branches:
      - main
jobs:
  ci-cd-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Clone jalien
        run: |
          cd ${{ github.workspace }}
          cd ..
          git clone https://gitlab.cern.ch/jalien/jalien
      - name: Clone jalien-setup
        run: |
          cd ${{ github.workspace }}
          cd ..
          git clone https://github.com/FYP-Jalien/jalien-setup
      - name: Create .env for test-suite
        run: |
          cd ${{ github.workspace }}
          cd ..
          echo "
          export SHARED_VOLUME_PATH=$(pwd)/SHARED_VOLUME
          export JALIEN_SETUP_PATH=$(pwd)/jalien-setup
          export JALIEN_PATH=$(pwd)/jalien
          export CONTAINER_NAME_CE=shared_volume_JCentral-dev-CE_1
          export CONTAINER_NAME_CENTRAL=shared_volume_JCentral-dev_1
          export CONTAINER_NAME_SCHEDD=shared_volume_schedd_1
          export CONTAINER_NAME_SE=shared_volume_JCentral-dev-SE_1
          export CONTAINER_NAME_WORKER=shared_volume_worker1_1
          export SCRIPT_DIR=$(pwd)/test-suite
          export SAMPLE_JDL_PATH=$(pwd)/test-suite/files/sample_test.jdl
          export TESTSCRIPT_PATH=$(pwd)/test-suite/files/testscript_test.sh
          export OUT_CSV_PATH=$(pwd)/test-suite/files/out.csv
          export SUMMARY_CSV_PATH=$(pwd)/test-suite/files/summary.csv
          " >> ${{ github.workspace }}/../test-suite/.env
      - name: Update /etc/hosts
        run: |
          sudo bash -c "echo '
          127.0.0.1       JCentral-dev
          127.0.0.1       JCentral-dev-SE
          172.18.0.2      alice-jcentral.cern.ch
          ' >> /etc/hosts"
      - name: Install dependencies required for alien.py
        run: |
          sudo apt update
          sudo apt install libx11-6 environment-modules
      - name: Install alien.py
        run: |
          sudo apt install python3-xrootd
          pip install xrootd
          pip install alienpy
      - name: Install xrootd
        run: |
          sudo apt install xrootd-client xrootd-server python3-xrootd

      - name: Run host specific tests
        run: |
          cd ${{ github.workspace }}/../test-suite
          ./index.sh --host-only
      - name: Create config.sh for bash
        run: |
          cd ${{ github.workspace }}
          cd ..
          echo "
          export BASE_DIR=$(pwd)
          export SCRIPT_DIR=$(pwd)/jalien-setup/bash
          export SHARED_VOLUME=$(pwd)/SHARED_VOLUME
          export JALIEN=$(pwd)/jalien
          export JALIEN_SETUP=$(pwd)/jalien-setup
          export JALIEN_SOURCE=https://gitlab.cern.ch/jalien/jalien
          export JALIEN_SETUP_SOURCE=https://github.com/FYP-Jalien/jalien-setup
          export CE_NAME=shared_volume_JCentral-dev-CE_1
          export JCENTRAL_NAME=shared_volume_JCentral-dev_1
          export SCHEDD_NAME=shared_volume_schedd_1
          export SE_NAME=shared_volume_JCentral-dev-SE_1
          export WORKER_NAME=shared_volume_worker1_1
          " >> ${{ github.workspace }}/../jalien-setup/bash/config/config.sh
      - name: Run jalien-setup bash scripts
        run: |
          cd ${{ github.workspace }}/../jalien-setup/bash
          ./start.sh --shared
      - name: Run test-suite
        run: |
          cd ${{ github.workspace }}/../test-suite
          ./index.sh --no-error-on-exit
